### ISSUE TITLE
Invalid tag <rticle> and unneeded usage of <table>

### ISSUE THREAD

**Issue by heywhahappnd** [maximkacmm/sports-app-landing#5]
https://github.com/maximkacmm/sports-app-landing/blob/f7ac35ba286e039bdd7ab3346828fa492955b81a/index.html#L106-L137

Вместо article напиши лучше section, table вообще не используй , замени лучше на обычный ul>li

**Comment by maximkacmm** [comment]
<rticle> заменил на <section>
 убрал <table> добавил ul>li
