### ISSUE TITLE
Use <ul> 

### ISSUE THREAD

**Issue by heywhahappnd** [maximkacmm/sports-app-landing#9]
https://github.com/maximkacmm/sports-app-landing/blob/f7ac35ba286e039bdd7ab3346828fa492955b81a/index.html#L168-L174

Для download support privacy developers используй один ul. для социалок другой ul
в итоге должно у тебя получиться  nav, в котором два ul

**Comment by maximkacmm** [comment]
добавил 2 ul и  li
